### ISSUE TITLE
Possible failure in shs1_create_client_auth

### ISSUE THREAD

**Issue by snej** [AljoschaMeyer/shs1-c#3]
In shs1_create_client_auth, if the initial call to crypto_scalarmult fails, the function gives up by returning false:

https://github.com/sunrise-choir/shs1-c/blob/ff220687d8e01fe54d5b2f2612ad9e2c08f0c47c/src/shs1.c#L94

Unfortunately the return value is an error code not a boolean, so returning false, i.e. 0, indicates _success_ to the caller. Which is bad news since the caller will be sending uninitialized garbage as the challenge.

I’m not sure under what circumstances crypto_scalarmult can fail, but this seems worth fixing.

**Comment by AljoschaMeyer** [comment]
Ouch, good catch. @pietgeursen do you know whether this affects any sunrise choir code?
